In [38]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("airlines_reviews.csv")
df

,Title,Name,Review Date,Airline,Verified,Reviews,Type of Traveller,Month Flown,Route,Class,Seat Comfort,Staff Service,Food & Beverages,Inflight Entertainment,Value For Money,Overall Rating,Recommended
0,Flight was amazing,Alison Soetantyo,2024-03-01,Singapore Airlines,True,Flight was amazing. The crew onboard this fl...,Solo Leisure,December 2023,Jakarta to Singapore,Business Class,4,4,4,4,4,9,yes
1,seats on this aircraft are dreadful,Robert Watson,2024-02-21,Singapore Airlines,True,Booking an emergency exit seat still meant h...,Solo Leisure,February 2024,Phuket to Singapore,Economy Class,5,3,4,4,1,3,no
2,Food was plentiful and tasty,S Han,2024-02-20,Singapore Airlines,True,Excellent performance on all fronts. I would...,Family Leisure,February 2024,Siem Reap to Singapore,Economy Class,1,5,2,1,5,10,yes
3,“how much food was available,D Laynes,2024-02-19,Singapore Airlines,True,Pretty comfortable flight considering I was f...,Solo Leisure,February 2024,Singapore to London Heathrow,Economy Class,5,5,5,5,5,10,yes
4,“service was consistently good”,A Othman,2024-02-19,Singapore Airlines,True,The service was consistently good from start ...,Family Leisure,February 2024,Singapore to Phnom Penh,Economy Class,5,5,5,5,5,10,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8095,an uneventful flight,N Vickers,2016-06-20,Korean Air,True,"KE124, Brisbane to Incheon (A330) and KE867,...",Business,June 2016,BNE to ULN via ICN,Economy Class,5,4,5,3,4,7,yes
8096,Korean Air always impresses,Kim Holloway,2016-06-12,Korean Air,False,Our recent flight was our fourth trip to the...,Couple Leisure,June 2016,SYD to LHR via ICN,Economy Class,3,5,5,4,5,10,yes
8097,didn’t offer anything,C Clark,2016-06-06,Korean Air,True,I flew Korean Air from Bali to Seoul in Pres...,Business,April 2016,DPS to ICN,Business Class,4,5,5,5,1,2,no
8098,appreciated the service onboard,E Petan,2016-04-21,Korean Air,False,Seoul to Paris with Korean Air. I am traveli...,Business,April 2016,ICN to CDG,Business Class,5,1,3,4,5,10,yes
8099,genuinely friendly staff,D Lanor,2016-04-12,Korean Air,False,The 13 hour flight in Business class from Se...,Business,April 2016,ICN to YYZ,Business Class,3,5,3,3,5,10,yes

In [ ]:
df.describe()

,Seat Comfort,Staff Service,Food & Beverages,Inflight Entertainment,Value For Money,Overall Rating
count,8100.000000,8100.000000,8100.000000,8100.000000,8100.000000,8100.000000
mean,3.414815,3.569877,3.384074,3.636790,3.148642,5.632469
std,1.397183,1.527436,1.455694,1.309564,1.589377,3.523664
min,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000
25%,2.000000,2.000000,2.000000,3.000000,1.000000,2.000000
50%,4.000000,4.000000,4.000000,4.000000,3.000000,6.000000
75%,5.000000,5.000000,5.000000,5.000000,5.000000,9.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000,10.000000

In [ ]:
df.isnull().sum().sum()

0

In [ ]:
df.duplicated().sum()

0

In [ ]:
a = df.shape
print(f"Rows: {a[0]} and Columns: {a[1]}")

Rows: 8100 and Columns: 17

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8100 entries, 0 to 8099
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   8100 non-null   object
 1   Name                    8100 non-null   object
 2   Review Date             8100 non-null   object
 3   Airline                 8100 non-null   object
 4   Verified                8100 non-null   object
 5   Reviews                 8100 non-null   object
 6   Type of Traveller       8100 non-null   object
 7   Month Flown             8100 non-null   object
 8   Route                   8100 non-null   object
 9   Class                   8100 non-null   object
 10  Seat Comfort            8100 non-null   int64
 11  Staff Service           8100 non-null   int64
 12  Food & Beverages        8100 non-null   int64
 13  Inflight Entertainment  8100 non-null   int64
 14  Value For Money         8100 non-null   int64
 15  Overall Rating          8100 non-null   int64
 16  Recommended             8100 non-null   object
dtypes: int64(6), object(11)
memory usage: 1.1+ MB

In [6]:
label_encoder = LabelEncoder()

# Fit and transform the 'Class' column
df['Class'] = label_encoder.fit_transform(df['Class'])

# Verify the label encoding by displaying the first few rows
print(df.head())

                                  Title              Name Review Date  \
0                    Flight was amazing  Alison Soetantyo  2024-03-01
1  seats on this aircraft are dreadful      Robert Watson  2024-02-21
2          Food was plentiful and tasty             S Han  2024-02-20
3          “how much food was available          D Laynes  2024-02-19
4       “service was consistently good”         A Othman   2024-02-19

              Airline Verified  \
0  Singapore Airlines     True
1  Singapore Airlines     True
2  Singapore Airlines     True
3  Singapore Airlines     True
4  Singapore Airlines     True

                                             Reviews Type of Traveller  \
0    Flight was amazing. The crew onboard this fl...      Solo Leisure
1    Booking an emergency exit seat still meant h...      Solo Leisure
2    Excellent performance on all fronts. I would...    Family Leisure
3   Pretty comfortable flight considering I was f...      Solo Leisure
4   The service was consistently good from start ...    Family Leisure

     Month Flown                         Route  Class  Seat Comfort  \
0  December 2023          Jakarta to Singapore      0             4
1  February 2024           Phuket to Singapore      1             5
2  February 2024        Siem Reap to Singapore      1             1
3  February 2024  Singapore to London Heathrow      1             5
4  February 2024       Singapore to Phnom Penh      1             5

   Staff Service  Food & Beverages  Inflight Entertainment  Value For Money  \
0              4                 4                       4                4
1              3                 4                       4                1
2              5                 2                       1                5
3              5                 5                       5                5
4              5                 5                       5                5

   Overall Rating Recommended
0               9         yes
1               3          no
2              10         yes
3              10         yes
4              10         yes

In [19]:
x = df.drop(["Title", "Name", "Review Date", "Airline", "Verified", "Reviews", "Type of Traveller", "Month Flown", "Route", "Recommended"], axis = 1)

In [20]:
y = df["Recommended"]

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [22]:
model = LogisticRegression()

In [23]:
model.fit(x_train, y_train)

LogisticRegression()

In [24]:
pred = model.predict(x_test)

In [27]:
pred

array(['yes', 'yes', 'no', ..., 'yes', 'yes', 'yes'], dtype=object)

In [31]:
accuracy = accuracy_score(y_test, pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.94

In [34]:
recall = recall_score(y_test, pred ,pos_label='yes')
print(f"Recall: {recall:.2f}")

Recall: 0.95

In [37]:
precision = precision_score(y_test, pred, pos_label='yes')
print(f"Precision: {precision:.2f}")

Precision: 0.95

In [39]:
f1 = f1_score(y_test, pred, pos_label='yes')
print(f"F1 Score: {f1:.2f}")

F1 Score: 0.95